/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Color;

import bota.BotaoArredondado;
/**
 *
 * @author Aluno.Manha
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        JLabelTutorial.setOpaque(true);
        JLabelTutorial.setBackground(Color.black);
        JLabelTutorial.setForeground(Color.white);
        JlabelExercicios.setOpaque(true);
        JlabelExercicios.setBackground(Color.black);
        JlabelExercicios.setForeground(Color.WHITE);
        JLabelSimu.setOpaque(true);
        JLabelSimu.setBackground(Color.black);
        JLabelSimu.setForeground(Color.WHITE);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel = new javax.swing.JPanel();
        nav = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JLabelTutorial = new javax.swing.JLabel();
        JlabelExercicios = new javax.swing.JLabel();
        JLabelSimu = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        JLabelModulo = new javax.swing.JLabel();
        Jlabel2Modulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        JBotaoSimulado = new javax.swing.JButton();
        JBotaoAprender = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Interface");
        setResizable(false);

        painel.setBackground(new java.awt.Color(255, 255, 255));
        painel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nav.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/logointerface.png"))); // NOI18N

        JLabelTutorial.setText("       TUTORIAL");
        JLabelTutorial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JLabelTutorial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JLabelTutorialMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JLabelTutorialMouseExited(evt);
            }
        });

        JlabelExercicios.setText("     EXERCÍCIOS");
        JlabelExercicios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JlabelExercicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JlabelExerciciosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JlabelExerciciosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JlabelExerciciosMouseExited(evt);
            }
        });

        JLabelSimu.setText("      SIMULADO");
        JLabelSimu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JLabelSimu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JLabelSimuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JLabelSimuMouseExited(evt);
            }
        });

        javax.swing.GroupLayout navLayout = new javax.swing.GroupLayout(nav);
        nav.setLayout(navLayout);
        navLayout.setHorizontalGroup(
            navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JLabelTutorial, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JlabelExercicios, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLabelSimu, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(551, Short.MAX_VALUE))
        );
        navLayout.setVerticalGroup(
            navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
            .addGroup(navLayout.createSequentialGroup()
                .addComponent(JLabelTutorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(navLayout.createSequentialGroup()
                .addComponent(JlabelExercicios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(navLayout.createSequentialGroup()
                .addComponent(JLabelSimu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        painel.add(nav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 70));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        JLabelModulo.setForeground(new java.awt.Color(255, 255, 255));
        JLabelModulo.setText("1 MÓDULO");
        JLabelModulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLabelModuloMouseClicked(evt);
            }
        });

        Jlabel2Modulo.setForeground(new java.awt.Color(255, 255, 255));
        Jlabel2Modulo.setText("2 MÓDULO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(JLabelModulo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(Jlabel2Modulo)
                .addContainerGap(738, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(JLabelModulo, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addComponent(Jlabel2Modulo, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
        );

        painel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 970, 30));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 57)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Learn More");
        painel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 340, 80));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/brmodelcerto.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 360, 340));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MODELAGEM");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Try yourself");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 360, 40));

        painel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 420, 460));

        JBotaoSimulado.setBackground(new java.awt.Color(0, 0, 0));
        JBotaoSimulado.setFont(JBotaoSimulado.getFont().deriveFont(JBotaoSimulado.getFont().getStyle() | java.awt.Font.BOLD, JBotaoSimulado.getFont().getSize()+2));
        JBotaoSimulado.setForeground(new java.awt.Color(255, 255, 255));
        JBotaoSimulado.setText("SIMULADO");
        JBotaoSimulado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        painel.add(JBotaoSimulado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 280, 60));

        JBotaoAprender.setBackground(new java.awt.Color(0, 0, 0));
        JBotaoAprender.setFont(JBotaoAprender.getFont().deriveFont(JBotaoAprender.getFont().getStyle() | java.awt.Font.BOLD, JBotaoAprender.getFont().getSize()+2));
        JBotaoAprender.setForeground(new java.awt.Color(255, 255, 255));
        JBotaoAprender.setText("APRENDER MODELAGEM");
        JBotaoAprender.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        painel.add(JBotaoAprender, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 280, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JLabelTutorialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLabelTutorialMouseEntered
        JLabelTutorial.setBackground(new Color(255, 255, 255));
        JLabelTutorial.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_JLabelTutorialMouseEntered

    private void JLabelTutorialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLabelTutorialMouseExited
        JLabelTutorial.setBackground(new Color(0, 0, 0));
        JLabelTutorial.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_JLabelTutorialMouseExited

    private void JlabelExerciciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlabelExerciciosMouseClicked


    }//GEN-LAST:event_JlabelExerciciosMouseClicked

    private void JlabelExerciciosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlabelExerciciosMouseEntered
        JlabelExercicios.setBackground(new Color(255, 255, 255));
        JlabelExercicios.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_JlabelExerciciosMouseEntered

    private void JlabelExerciciosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlabelExerciciosMouseExited
        JlabelExercicios.setBackground(new Color(0, 0, 0));
        JlabelExercicios.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_JlabelExerciciosMouseExited

    private void JLabelSimuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLabelSimuMouseEntered
        JLabelSimu.setBackground(new Color(255, 255, 255));
        JLabelSimu.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_JLabelSimuMouseEntered

    private void JLabelSimuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLabelSimuMouseExited
        JLabelSimu.setBackground(new Color(0, 0, 0));
        JLabelSimu.setForeground(new Color(255, 255, 255));

    }//GEN-LAST:event_JLabelSimuMouseExited

    private void JLabelModuloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLabelModuloMouseClicked

    }//GEN-LAST:event_JLabelModuloMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBotaoAprender;
    private javax.swing.JButton JBotaoSimulado;
    private javax.swing.JLabel JLabelModulo;
    private javax.swing.JLabel JLabelSimu;
    private javax.swing.JLabel JLabelTutorial;
    private javax.swing.JLabel Jlabel2Modulo;
    private javax.swing.JLabel JlabelExercicios;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel nav;
    private javax.swing.JPanel painel;
    // End of variables declaration//GEN-END:variables
}
